package edu.ucsd.crbs.probabilitymapviewer.util;

import java.util.List;
import java.util.Map;

/**
 * Instances of this class allow caller to invoke a command line program.
 * 
 * @author Christopher Churas <churas@ncmir.ucsd.edu>
 */
public interface RunCommandLineProcess {
    
    
    public void setWorkingDirectory(final String workingDir);

    public void setEnvironmentVariables(Map<String, String> envVars);

    public String getLastCommand();
    
    /**
     * Runs command line program specified by first argument.
     * @param command - First argument should be full path to command followed by arguments
     * @return String containing standard error and standard out generated by program.  
     * @throws java.lang.Exception if there was an error invoking the process or if the process returns non zero exit code
     */
    public String runCommandLineProcess(String... command) throws Exception;
    
    public String runCommandLineProcess(List<String> cmdAndArgs) throws Exception;
}
